{% set name = "city2graph" %}
{% set version = "0.1.1" %}
{% set python_min = "3.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/city2graph-{{ version }}.tar.gz
  sha256: 1fcece53e4bdbce34ffed90ce316b08c2a2092a0a0746699066bf5dca3908a71

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - python >={{ python_min }}
    - networkx >=2.8
    - osmnx >=2.0.3
    - shapely >=2.1.0
    - geopandas >0.12.0
    - libpysal >=4.12.1
    - momepy
    - overturemaps

test:
  imports:
    - city2graph
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://city2graph.net
  summary: Transform geospatial relations into graph representations designed for spatial analysis and Graph Neural Networks (GNNs).
  license: BSD-3-Clause
  license_file: LICENSE
  description: |
    city2graph is a Python library for converting datasets of geospatial relations into
    graphs. It is designed to facilitate graph data analytics in particular for urban
    studies and spatial analysis. It supports PyTorch Geometric to enable graph
    representation learning, such as Graph Neural Networks (GNNs).
    
    Key features include:
    - Construct graphs from morphological datasets (buildings, streets, land use)
    - Construct graphs from transportation datasets (public transport networks)
    - Construct graphs from contiguity datasets (land use, land cover, administrative boundaries)
    - Construct graphs from mobility datasets (bike-sharing, migration, pedestrian flows)
    - Convert geospatial data into tensors for graph representation learning
    - Support for various proximity methods (KNN, Waxman, fixed radius)
    - Integration with PyTorch Geometric's Data and HeteroData formats
    
    The library enables urban researchers and data scientists to transform complex
    geospatial relationships into graph structures suitable for network analysis
    and machine learning applications.
  doc_url: https://city2graph.net
  dev_url: https://github.com/c2g-dev/city2graph

extra:
  recipe-maintainers:
    - yu-ta-sato
